# Site settings
title: "Vicent Sus"
description: "e.nig.ma"

author: Vicent Sus
email: johnny@appleseed.com
twitter_username: _HairForceOne
github_username: mkchoi212

baseurl: "/vicent" # the subpath of your site, e.g. /blog
url: "https://e-nig-ma.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

